# Generated by Django 5.2 on 2025-05-15 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('license_plate', models.CharField(max_length=9, verbose_name='Гос. номер')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
                ('rental_cost_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за день')),
                ('status', models.CharField(max_length=15, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('driver_license', models.CharField(max_length=10, verbose_name='Водительское удостоверение')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(verbose_name='Дата обслуживания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('mileage', models.IntegerField(verbose_name='Пробег на момент обслуживания')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.car', verbose_name='Авто')),
            ],
            options={
                'verbose_name': 'Обслуживание',
                'verbose_name_plural': 'Обслуживания',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('duration_days', models.IntegerField(verbose_name='Дней аренды')),
                ('cost_per_day', models.IntegerField(verbose_name='Стоимость в день')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого')),
                ('status', models.CharField(max_length=15, verbose_name='Статус')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.car', verbose_name='Автомобиль')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_type', models.CharField(max_length=15, verbose_name='Тип оплаты')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.client', verbose_name='Клиент')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.rental', verbose_name='Аренда')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, verbose_name='Доп. услуга')),
                ('service_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.rental', verbose_name='Аренда')),
            ],
            options={
                'verbose_name': 'Дополнительная услуга',
                'verbose_name_plural': 'Дополнительные услуги',
            },
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_type', models.TextField(verbose_name='Тип повреждения')),
                ('repair_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость ремонта')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.car', verbose_name='Авто')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.rental', verbose_name='Аренда')),
            ],
            options={
                'verbose_name': 'Повреждение',
                'verbose_name_plural': 'Повреждения',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
