# Generated by Django 5.2 on 2025-05-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='total_cost',
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='client',
            name='driver_license',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Водительское удостоверение'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='mileage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пробег на момент обслуживания'),
        ),
    ]
