# Generated by Django 5.2 on 2025-05-22 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_alter_rental_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='damage',
            options={},
        ),
        migrations.AlterField(
            model_name='damage',
            name='car',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='rentals.car', verbose_name='Автомобиль'),
        ),
    ]
