# Generated by Django 5.2 on 2025-05-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_alter_damage_options_alter_car_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='duration_days',
            field=models.IntegerField(default=1, editable=False, verbose_name='Длительность аренды'),
        ),
        migrations.AddField(
            model_name='rental',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Итого'),
        ),
    ]
