# Generated by Django 5.2 on 2025-05-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_rental_duration_days_rental_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='duration_days',
            field=models.IntegerField(editable=False, verbose_name='Длительность аренды'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Итого'),
        ),
    ]
